name:                hid-learn
version:             0.1.0.0
github:              "githubuser/hid-learn"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hid-learn#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: 
      - src/ch02/radar
      - src/ch05
      - expr/rpn
    exposed-modules: Radar
    other-modules: []
    dependencies:
      - fmt
      - random
      - mtl
      - extra
      - text

executables:
  hid-learn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hid-learn
  vocab01:
    main: vocab01.hs
    source-dirs: src/ch01
    dependencies:
      - text
  vocab02:
    main: vocab02.hs
    source-dirs: src/ch01
    dependencies:
      - text
  vocab03:
    main: vocab03.hs
    source-dirs: src/ch01
    dependencies:
      - text
      - fmt
  sumlist:
    main: sumlist.hs
    source-dirs: src/ch05
    dependencies:
      - text
      - fmt
      - mtl
  filec:
    main: filecount.hs
    source-dirs: src/ch05
    dependencies:
      - text
      - fmt
      - mtl
      - extra
  eval1:
    source-dirs: expr/rpn
    main: EvalRPNExceptT.hs
    dependencies:
      - mtl >= 2.0 && < 2.3
      - text
      - text-show
  du:
    source-dirs: du
    main: Main.hs
    dependencies:
      - mtl
      - text
      - unix-compat
      - directory
      - filepath
      - extra
      - text-show
      - optparse-applicative

    default-extensions: 
      - OverloadedStrings
      - RecordWildCards
      - NamedFieldPuns
    
  

tests:
  hid-learn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hid-learn
  radar-test:
    source-dirs: test/radar
    main: Test.hs
    dependencies:
      - random >= 1.2
      - hid-learn