name:                stackquotes
version:             0.1.0.0
github:              "githubuser/stackquotes"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stackquotes#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - time
  - fmt
  - colonnade
  - blaze-html
  - blaze-colonnade
  - Chart
  - Chart-diagrams >= 1.9.4
  - cassava
  - optparse-applicative

library:
  source-dirs: src

executables:
  stackquotes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stackquotes

tests:
  stackquotes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stackquotes
